postgres:
  image: postgres
  container_name: postgres
  restart: always
  environment:
    POSTGRES_PASSWORD: postgres
  hostname: postgres
  ports:
    - 5432:5432
  # entrypoint:
  #   - /entrypoint.sh
  volumes:
    - ./postgres/database:/var/lib/postgresql/data
    # - ./postgres/data.sql:/data.sql
    # - ./postgres/pipeline_data.sql:/pipeline_data.sql
    # - ./postgres/entrypoint.sh:/entrypoint.sh

pgadmin-compose:
  image: dpage/pgadmin4
  container_name: pgadmin4
  environment: 
    PGADMIN_DEFAULT_EMAIL: "test@gmail.com"
    PGADMIN_DEFAULT_PASSWORD: "test123!"
  ports: 
    - "8000:80"
  links: 
    - postgres    

portainer:
  image:  portainer/portainer-ce
  container_name: portainer
  command: -H unix:///var/run/docker.sock
  ports:
      - "9000:9000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./portainer/data:/data

development:
  #image: debian:buster-slim
  build: ./development
  container_name: development
  ports:
    - "2222:22"
  #volumes:
  #  - ./development/deployment :/opt/deployment

