# Docker-compose
version: '3.7'

services:

  nginx:
    image: nginx:alpine
    container_name: proxy
    volumes:
      - ./conf/nginx/www:/usr/share/nginx/html:ro
      - ./conf/nginx/conf:/etc/nginx/conf.d
      - ./conf/nginx/ssl/rootCA.crt:/etc/nginx/ssl/rootCA.crt:ro
      - ./conf/nginx/ssl/rootCA.key:/etc/nginx/ssl/rootCA.key:ro
      - ./data/nginx/dhparam:/etc/nginx/dhparam
      - ./data/nginx/vhost:/etc/nginx/vhost.d
      - ./data/nginx/certs:/etc/nginx/certs
      - /run/docker.sock:/tmp/docker.sock:ro
    restart: "always"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    hostname: postgres
    ports:
      - 5044:5432
    # entrypoint:
    #   - /entrypoint.sh
    networks:
      - backend
    volumes:
      - ./postgres/database:/var/lib/postgresql/data
      # - ./postgres/data.sql:/data.sql
      # - ./postgres/pipeline_data.sql:/pipeline_data.sql
      # - ./postgres/entrypoint.sh:/entrypoint.sh

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment: 
      PGADMIN_DEFAULT_EMAIL: "admin@visiodesk.net"
      PGADMIN_DEFAULT_PASSWORD: "admin"
      PGADMIN_LISTEN_PORT: 80
    ports:
      - "8080:80"
    links: 
      - postgres    

  portainer:
    image:  portainer/portainer-ce
    container_name: portainer
    command: -H unix:///var/run/docker.sock
    ports:
      - "9000:9000"
    networks:
      - backend
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data

  #development:
    #image: debian:buster-slim
    #build: ./development
    #container_name: development
    #ports:
    #  - "5005:22"
    #volumes:
    #  - ./development/deployment :/opt/deployment

  rabbit1:
    image: rabbitmq:3-management
    hostname: rabbit1
    container_name: rabbit1
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST: "/rabbit/"
    ports:
      - 5045:15675
      - 5083:1883
      - 5183:8883
    networks:
      - backend
    user: root
    volumes:
      - ./conf/rabbit/enabled_plugins:/etc/rabbitmq/enabled_plugins
      - ./data/rabbit:/var/lib/rabbitmq
      - ./log/rabbit:/var/log/rabbitmq

networks:

  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.16.0/24
          gateway: 172.16.16.1
          ip_range: 172.16.0.0/24
