grafana:
  image: grafana/grafana
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - postgres
  environment:
    GF_USERS_DEFAULT_THEME: "light"
  volumes:
    - ./grafana/postgres.yml:/etc/grafana/provisioning/datasources/postgres.yml
    - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    - ./grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json

postgres:
  image: postgres
  container_name: postgres
  ports:
    - 5432:5432
  environment:
    POSTGRES_USER: ​'postgres​'
    POSTGRES_PASSWORD: 'postgres'
    POSTGRES_DB: 'postgres'
  # entrypoint:
  #   - ./postgres/entrypoint.sh
  volumes:
    - ./postgres/database:/var/lib/postgresql/data
    - ./postgres/data.sql:/data.sql
    - ./postgres/pipeline_data.sql:/pipeline_data.sql
    - ./postgres/entrypoint.sh:/docker-entrypoint-initdb.d/entrypoint.sh

portainer:
  image:  portainer/portainer-ce
  container_name: portainer
  command: -H unix:///var/run/docker.sock
  ports:
      - "9000:9000"
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock