grafana:
  build: ./grafana
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - postgres
  environment:
    GF_USERS_DEFAULT_THEME: "light"

postgres:
  image: postgres
  container_name: postgres
  ports:
      - 5432:5432

testdata:
  build: ./testdata
  links:
    - postgres

portainer:
  image:  portainer/portainer-ce
  container_name: portainer
  command: -H unix:///var/run/docker.sock
  ports:
      - 9000:9000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock