grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - postgres
  volumes: 
    - ./grafana/postgres.yml:/etc/grafana/provisioning/datasources/postgres.yml
    - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
    - ./grafana/dashboard.json:/var/lib/grafana/dashboards/dashboard.json

  environment:
    GF_USERS_DEFAULT_THEME: "light"

postgres:
  image: postgres:latest
  container_name: postgres

testdata:
  build: ./testdata
  links:
    - postgres