grafana:
  build: ./grafana
  container_name: grafana
  ports:
    - "3000:3000"
  links:
    - postgres
  environment:
    GF_USERS_DEFAULT_THEME: "light"

postgres:
  image: postgres
  container_name: postgres

testdata:
  build: ./testdata
  links:
    - postgres